version: "3"

services:
  generator:
    build:
        context: .
    command:
      - /usr/local/bin/generator 
      - data
      - --timer=0 # Use 0 when testing
    volumes:
      - ./data:/app/data
    ports:
      - "9999:9999"

  tracker:
    build:
      context: .
    command:
      - /usr/local/bin/generator 
      - track
      - --custodian
      - http://generator:9999/custodian/
    ports:
      - "9998:9998"
